apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: regapp
  name: regapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: regapp
  type: NodePort
status:
  loadBalancer: {}
